### ISSUE TITLE
developer app list not return

### ISSUE THREAD

**Issue by tanish-kr** [tatsu07/store_api#24]
```
.F/Users/tatsunorinishikori/workspace/ruby/store_api/lib/store_api/request.rb:92:in `request'
/Users/tatsunorinishikori/workspace/ruby/store_api/lib/store_api/request.rb:30:in `post'
/Users/tatsunorinishikori/workspace/ruby/store_api/lib/store_api/google_play/apps/developer.rb:25:in `block in initialize'
/Users/tatsunorinishikori/workspace/ruby/store_api/lib/store_api/google_play/apps/developer.rb:21:in `each'
/Users/tatsunorinishikori/workspace/ruby/store_api/lib/store_api/google_play/apps/developer.rb:21:in `initialize'
/Users/tatsunorinishikori/workspace/ruby/store_api/spec/store_api/google_play/apps/developer_spec.rb:8:in `new'
/Users/tatsunorinishikori/workspace/ruby/store_api/spec/store_api/google_play/apps/developer_spec.rb:8:in `block (2 levels) in <top (required)>'
/Users/tatsunorinishikori/.anyenv/envs/rbenv/versions/2.6.0/gemsets/store_api/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:254:in `instance_exec'
/Users/tatsunorinishikori/.anyenv/envs/rbenv/versions/2.6.0/gemsets/store_api/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:254:in `block in run'
/Users/tatsunorinishikori/.anyenv/envs/rbenv/versions/2.6.0/gemsets/store_api/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:500:in `block in with_around_and_singleton_context_hooks'
/Users/tatsunorinishikori/.anyenv/envs/rbenv/versions/2.6.0/gemsets/store_api/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:457:in `block in with_around_example_hooks'
/Users/tatsunorinishikori/.anyenv/envs/rbenv/versions/2.6.0/gemsets/store_api/gems/rspec-core-3.8.0/lib/rspec/core/hooks.rb:464:in `block in run'
/Users/tatsunorinishikori/.anyenv/envs/rbenv/versions/2.6.0/gemsets/store_api/gems/rspec-core-3.8.0/lib/rspec/core/hooks.rb:602:in `run_around_example_hooks_for'
/Users/tatsunorinishikori/.anyenv/envs/rbenv/versions/2.6.0/gemsets/store_api/gems/rspec-core-3.8.0/lib/rspec/core/hooks.rb:464:in `run'
/Users/tatsunorinishikori/.anyenv/envs/rbenv/versions/2.6.0/gemsets/store_api/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:457:in `with_around_example_hooks'
/Users/tatsunorinishikori/.anyenv/envs/rbenv/versions/2.6.0/gemsets/store_api/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:500:in `with_around_and_singleton_context_hooks'
/Users/tatsunorinishikori/.anyenv/envs/rbenv/versions/2.6.0/gemsets/store_api/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:251:in `run'
/Users/tatsunorinishikori/.anyenv/envs/rbenv/versions/2.6.0/gemsets/store_api/gems/rspec-core-3.8.0/lib/rspec/core/example_group.rb:629:in `block in run_examples'
/Users/tatsunorinishikori/.anyenv/envs/rbenv/versions/2.6.0/gemsets/store_api/gems/rspec-core-3.8.0/lib/rspec/core/example_group.rb:625:in `map'
/Users/tatsunorinishikori/.anyenv/envs/rbenv/versions/2.6.0/gemsets/store_api/gems/rspec-core-3.8.0/lib/rspec/core/example_group.rb:625:in `run_examples'
/Users/tatsunorinishikori/.anyenv/envs/rbenv/versions/2.6.0/gemsets/store_api/gems/rspec-core-3.8.0/lib/rspec/core/example_group.rb:591:in `run'
/Users/tatsunorinishikori/.anyenv/envs/rbenv/versions/2.6.0/gemsets/store_api/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:116:in `block (3 levels) in run_specs'
/Users/tatsunorinishikori/.anyenv/envs/rbenv/versions/2.6.0/gemsets/store_api/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:116:in `map'
/Users/tatsunorinishikori/.anyenv/envs/rbenv/versions/2.6.0/gemsets/store_api/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:116:in `block (2 levels) in run_specs'
/Users/tatsunorinishikori/.anyenv/envs/rbenv/versions/2.6.0/gemsets/store_api/gems/rspec-core-3.8.0/lib/rspec/core/configuration.rb:1989:in `with_suite_hooks'
/Users/tatsunorinishikori/.anyenv/envs/rbenv/versions/2.6.0/gemsets/store_api/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:111:in `block in run_specs'
/Users/tatsunorinishikori/.anyenv/envs/rbenv/versions/2.6.0/gemsets/store_api/gems/rspec-core-3.8.0/lib/rspec/core/reporter.rb:74:in `report'
/Users/tatsunorinishikori/.anyenv/envs/rbenv/versions/2.6.0/gemsets/store_api/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:110:in `run_specs'
/Users/tatsunorinishikori/.anyenv/envs/rbenv/versions/2.6.0/gemsets/store_api/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:87:in `run'
/Users/tatsunorinishikori/.anyenv/envs/rbenv/versions/2.6.0/gemsets/store_api/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:71:in `run'
/Users/tatsunorinishikori/.anyenv/envs/rbenv/versions/2.6.0/gemsets/store_api/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:45:in `invoke'
/Users/tatsunorinishikori/.anyenv/envs/rbenv/versions/2.6.0/gemsets/store_api/gems/rspec-core-3.8.0/exe/rspec:4:in `<top (required)>'
/Users/tatsunorinishikori/.anyenv/envs/rbenv/versions/2.6.0/gemsets/store_api/bin/rspec:23:in `load'
/Users/tatsunorinishikori/.anyenv/envs/rbenv/versions/2.6.0/gemsets/store_api/bin/rspec:23:in `<main>'
Server Error ! responce code = 502 response = <!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 502 (Server Error)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>502.</b> <ins>That’s an error.</ins>
  <p>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.  <ins>That’s all we know.</ins>
F....

Failures:

  1) StoreApi::GooglePlay::Apps::Details details test
     Failure/Error: puts 'title : ' + apps.title

     TypeError:
       no implicit conversion of nil into String
     # ./spec/store_api/google_play/apps/details_spec.rb:9:in `+'
     # ./spec/store_api/google_play/apps/details_spec.rb:9:in `block (2 levels) in <top (required)>'

  2) StoreApi::GooglePlay::Apps::Developer developer app list test
     Failure/Error: expect(developer.apps_list.size).to be > 5

       expected: > 5
            got:   0
     # ./spec/store_api/google_play/apps/developer_spec.rb:10:in `block (2 levels) in <top (required)>'

Finished in 13.66 seconds (files took 0.8377 seconds to load)
7 examples, 2 failures

Failed examples:

rspec ./spec/store_api/google_play/apps/details_spec.rb:6 # StoreApi::GooglePlay::Apps::Details details test
rspec ./spec/store_api/google_play/apps/developer_spec.rb:6 # StoreApi::GooglePlay::Apps::Developer developer app list test

/Users/tatsunorinishikori/.anyenv/envs/rbenv/versions/2.6.0/gemsets/store_api/gems/simplecov-0.9.2/lib/simplecov/configuration.rb:193: warning: constant ::Fixnum is deprecated
[Coveralls] Outside the CI environment, not sending data.
/Users/tatsunorinishikori/.anyenv/envs/rbenv/versions/2.6.0/gemsets/store_api/gems/simplecov-0.9.2/lib/simplecov/configuration.rb:193: warning: constant ::Fixnum is deprecated
/Users/tatsunorinishikori/.anyenv/envs/rbenv/versions/2.6.0/gemsets/store_api/gems/simplecov-0.9.2/lib/simplecov/source_file.rb:29: warning: constant ::Fixnum is deprecated
/Users/tatsunorinishikori/.anyenv/envs/rbenv/versions/2.6.0/gemsets/store_api/gems/simplecov-0.9.2/lib/simplecov/source_file.rb:30: warning: constant ::Fixnum is deprecated

```

**Comment by tanish-kr** [comment]
This case is change node
